### ISSUE TITLE
jupyterlab-git is not in npm

### ISSUE THREAD

**Issue by oersted** [jupyterlab/jupyterlab-git#101]
Just run the first installation command in the README (`jupyter labextension install jupyterlab-git `) and got this error, it's pretty self-explanatory.

`npm ERR! 404 'jupyterlab-git' is not in the npm registry.`

Here's the whole thing:

```
⊨ jupyter labextension install jupyterlab-git                                                                                                                                                  (thesis) ~/M/S/thesis 
> npm pack jupyterlab-git
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'jupyterlab-git' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 4.9.0-3-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "pack" "jupyterlab-git"
npm ERR! cwd /home/oersted/.miniconda/envs/thesis/share/jupyter/lab/extensions/temp
npm ERR! node -v v4.8.2
npm ERR! npm -v 1.4.21
npm ERR! code E404
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/oersted/.miniconda/envs/thesis/share/jupyter/lab/extensions/temp/npm-debug.log
npm ERR! not ok code 0

Traceback (most recent call last):
  File "/home/oersted/.miniconda/envs/thesis/bin/jupyter-labextension", line 6, in <module>
    sys.exit(jupyterlab.labextensions.main())
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 167, in start
    super(LabExtensionApp, self).start()
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 57, in start
    for arg in self.extra_args]
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/labextensions.py", line 57, in <listcomp>
    for arg in self.extra_args]
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/commands.py", line 107, in install_extension
    run([get_npm_name(), 'pack', extension], cwd=target, logger=logger)
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/commands.py", line 71, in run
    raise error
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/site-packages/jupyterlab/commands.py", line 67, in run
    return check_output(cmd, **kwargs)
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "/home/oersted/.miniconda/envs/thesis/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['npm', 'pack', 'jupyterlab-git']' returned non-zero exit status 1

```

**Comment by ddavidebor** [comment]
https://github.com/fermiumlabs/data-chan-python/blob/master/wercker.yml may be useful if you want to set up a CI for releasing python packages

**Comment by ddavidebor** [comment]
https://github.com/fermiumlabs/data-chan-nodejs/blob/master/wercker.yml example of releasing with a CI

**Comment by ashutoshbondre** [comment]
Hi @oersted! We have not published our package to the npm registry yet. If you still want to install the extension, you would first want to clone the repository & run all the `README` commands inside the cloned directory. 

Apologies for the confusion, the `README` should have mentioned that explicitly.

**Comment by ellisonbg** [comment]
Adding this to the 0.3 milestone for JupyterCon. Let us know when you are ready to publish to npm as we have the crediential to do so under the @jupyterlab org.
