### ISSUE TITLE
Prevent `git rev-parse --show-origin` from running in some dirs

### ISSUE THREAD

**Issue by divyansshhh** [jupyterlab/jupyterlab-git#1162]
## Is your feature request related to a problem? Please describe.

We have a contents manager that prefixes **some** paths for some special handling (these aren't actual file system paths). When navigating into these "prefixed dirs", jupyterlab-git tries to run `git rev-parse --show-origin` which causes it to fail and litter the console. 

Log - 
```
[20220830 11:19:29:378 git.py:158 WARNING] Fail to execute ['git', 'rev-parse', '--show-prefix']
[20220830 11:19:29:378 git.py:158 WARNING] Traceback (most recent call last):
[20220830 11:19:29:378 git.py:158 WARNING]   File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/jupyterlab_git/git.py", line 144, in execute
[20220830 11:19:29:378 git.py:158 WARNING]     code, output, error = await current_loop.run_in_executor(
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/asyncio/futures.py", line 284, in __await__
[20220830 11:19:29:378 git.py:158 WARNING]     yield self  # This tells Task to wait for completion.
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/asyncio/tasks.py", line 304, in __wakeup
[20220830 11:19:29:378 git.py:158 WARNING]     future.result()
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/asyncio/futures.py", line 201, in result
[20220830 11:19:29:378 git.py:158 WARNING]     raise self._exception
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
[20220830 11:19:29:378 git.py:158 WARNING]     result = self.fn(*self.args, **self.kwargs)
[20220830 11:19:29:378 git.py:158 WARNING]   File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/jupyterlab_git/git.py", line 110, in call_subprocess
[20220830 11:19:29:378 git.py:158 WARNING]     process = subprocess.Popen(
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/subprocess.py", line 966, in __init__
[20220830 11:19:29:378 git.py:158 WARNING]     self._execute_child(args, executable, preexec_fn, close_fds,
[20220830 11:19:29:378 git.py:158 WARNING]   File "/opt/python/python-3.10/lib64/python3.10/subprocess.py", line 1842, in _execute_child
[20220830 11:19:29:379 git.py:158 WARNING]     raise child_exception_type(errno_num, err_msg, err_filename)
[20220830 11:19:29:379 git.py:158 WARNING] FileNotFoundError: [Errno 2] No such file or directory: '/gimme/hyd/u/choudhdi'
```

Here, `/gimme/hyd` is the prefix which is not an actual file system path and `/u/choudhdi` is the path.

## Describe the solution you'd like

One solution I can think of is allowing users to pass some `exclude` setting where they can define the regex for directories where this shouldn't run.

**Comment by divyansshhh** [comment]
Hi @fcollonval , thanks for giving pointers. I'll work on a PR for this.

**Comment by divyansshhh** [comment]
I've raised jupyterlab/jupyterlab-git#1163.
