### ISSUE TITLE
Does not work with RTC on JupyterLab 4.0?

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-git#1282]
Testing 0.55.0a0 on binder with RTC on:

https://mybinder.org/v2/gist/krassowski/847732eb6c16e168fb4c0b16d9706142/HEAD?urlpath=lab

RTC: is not a Git repository. To use Git, navigate to a local repository, initialize a repository here, or clone an existing repository.

![image](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/a62dbbe3-4f96-4e15-a50a-6eb0558e15ce)

Clicking Initialize:

```
Traceback (most recent call last): File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyterlab_git/git.py", line 184, in execute code, output, error = await current_loop.run_in_executor( File "/srv/conda/envs/notebook/lib/python3.10/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/srv/conda/envs/notebook/lib/python3.10/site-packages/jupyterlab_git/git.py", line 145, in call_subprocess process = subprocess.Popen( File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 971, in __init__ self._execute_child(args, executable, preexec_fn, close_fds, File "/srv/conda/envs/notebook/lib/python3.10/subprocess.py", line 1863, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: '/home/jovyan/rtc:'
```

Trying to download a repo:

![image](https://github.com/jupyterlab/jupyterlab-git/assets/5832902/88de5352-db26-4efe-9bbd-f2ef63eeda9d)

**Comment by Sieboldianus** [comment]
Using jupyterlab `4.3.4`, (jupytext `1.16.6`), collaboration-extension `3.1.0`, and jupyterlab-git `0.50.2`, the issue is back for me:

> RTC: is not a Git repository. To use Git, navigate to a local repository, initialize a repository here, or clone an existing repository.
