### ISSUE TITLE
npm install command don't work with this package

### ISSUE THREAD

**Issue by yougha54** [jupyterlab/jupyterlab-git#173]
Hello I cannot install jupyterlab-git, here what I get in the following log

 ```
info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\G30622\\miniconda3\\Library\\bin\\node.exe',
1 verbose cli   'C:\\Users\\G30622\\miniconda3\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.10.3
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly loadIdealTree Finishing
21 silly currentTree jupyterlab-git@0.1.0
21 silly currentTree +-- @angular/core@4.4.6
21 silly currentTree +-- @jupyterlab/application@0.10.0
21 silly currentTree +-- @jupyterlab/apputils@0.10.0
21 silly currentTree +-- @jupyterlab/cells@0.10.0
21 silly currentTree +-- @jupyterlab/codeeditor@0.10.0
21 silly currentTree +-- @jupyterlab/codemirror@0.10.0
21 silly currentTree +-- @jupyterlab/console@0.10.0
21 silly currentTree +-- @jupyterlab/coreutils@0.10.1
21 silly currentTree +-- @jupyterlab/docmanager@0.10.0
21 silly currentTree +-- @jupyterlab/docregistry@0.10.0
21 silly currentTree +-- @jupyterlab/filebrowser@0.10.0
21 silly currentTree +-- @jupyterlab/outputarea@0.10.0
21 silly currentTree +-- @jupyterlab/rendermime-interfaces@0.3.1
21 silly currentTree +-- @jupyterlab/rendermime@0.10.0
21 silly currentTree +-- @jupyterlab/services@0.49.0
21 silly currentTree +-- @jupyterlab/terminal@0.10.0
21 silly currentTree +-- @jupyterlab/theming@0.9.0
21 silly currentTree +-- @phosphor/algorithm@1.1.2
21 silly currentTree +-- @phosphor/application@1.5.0
21 silly currentTree +-- @phosphor/collections@1.1.2
21 silly currentTree +-- @phosphor/commands@1.4.0
21 silly currentTree +-- @phosphor/coreutils@1.3.0
21 silly currentTree +-- @phosphor/disposable@1.1.2
21 silly currentTree +-- @phosphor/domutils@1.1.2
21 silly currentTree +-- @phosphor/dragdrop@1.3.0
21 silly currentTree +-- @phosphor/keyboard@1.1.2
21 silly currentTree +-- @phosphor/messaging@1.2.2
21 silly currentTree +-- @phosphor/properties@1.1.2
21 silly currentTree +-- @phosphor/signaling@1.2.2
21 silly currentTree +-- @phosphor/virtualdom@1.1.2
21 silly currentTree +-- @phosphor/widgets@1.5.0
21 silly currentTree +-- @types/codemirror@0.0.38
21 silly currentTree +-- @types/marked@0.0.28
21 silly currentTree +-- @types/mathjax@0.0.31
21 silly currentTree +-- @types/quill@1.3.3
21 silly currentTree +-- @types/react-dom@15.5.6
21 silly currentTree | `-- @types/react@15.6.7
21 silly currentTree +-- @types/react@16.0.24
21 silly currentTree +-- @types/sanitize-html@1.14.0
21 silly currentTree +-- @types/text-encoding@0.0.30
21 silly currentTree +-- ajv@5.3.0
21 silly currentTree +-- ansi_up@1.3.0
21 silly currentTree +-- array-uniq@1.0.3
21 silly currentTree +-- asap@2.0.6
21 silly currentTree +-- balanced-match@1.0.0
21 silly currentTree +-- brace-expansion@1.1.8
21 silly currentTree +-- classnames@2.2.5
21 silly currentTree +-- clone@2.1.1
21 silly currentTree +-- co@4.6.0
21 silly currentTree +-- codemirror@5.31.0
21 silly currentTree +-- concat-map@0.0.1
21 silly currentTree +-- core-js@1.2.7
21 silly currentTree +-- core-util-is@1.0.2
21 silly currentTree +-- create-react-class@15.6.2
21 silly currentTree +-- date-arithmetic@3.1.0
21 silly currentTree +-- deconstruct-number-format@0.0.1
21 silly currentTree +-- deep-equal@1.0.1
21 silly currentTree +-- dom-helpers@2.4.0
21 silly currentTree +-- dom-serializer@0.1.0
21 silly currentTree | `-- domelementtype@1.1.3
21 silly currentTree +-- domelementtype@1.3.0
21 silly currentTree +-- domhandler@2.4.1
21 silly currentTree +-- domutils@1.6.2
21 silly currentTree +-- encoding@0.1.12
21 silly currentTree +-- entities@1.1.1
21 silly currentTree +-- eventemitter3@2.0.3
21 silly currentTree +-- extend@3.0.1
21 silly currentTree +-- fast-deep-equal@1.0.0
21 silly currentTree +-- fast-diff@1.1.2
21 silly currentTree +-- fast-json-stable-stringify@2.0.0
21 silly currentTree +-- fbjs@0.8.16
21 silly currentTree +-- format-number-with-string@0.0.2
21 silly currentTree +-- format-number@2.0.2
21 silly currentTree +-- fs.realpath@1.0.0
21 silly currentTree +-- glob@7.1.2
21 silly currentTree +-- htmlparser2@3.9.2
21 silly currentTree +-- iconv-lite@0.4.19
21 silly currentTree +-- inflight@1.0.6
21 silly currentTree +-- inherits@2.0.3
21 silly currentTree +-- invariant@2.2.2
21 silly currentTree +-- is-stream@1.1.0
21 silly currentTree +-- isarray@1.0.0
21 silly currentTree +-- isomorphic-fetch@2.2.1
21 silly currentTree +-- jquery@2.2.4
21 silly currentTree +-- js-tokens@3.0.2
21 silly currentTree +-- json-schema-traverse@0.3.1
21 silly currentTree +-- json-stable-stringify@1.0.1
21 silly currentTree +-- jsonify@0.0.0
21 silly currentTree +-- lodash.escaperegexp@4.1.2
21 silly currentTree +-- lodash@4.17.4
21 silly currentTree +-- loose-envify@1.3.1
21 silly currentTree +-- marked@0.3.6
21 silly currentTree +-- minimatch@3.0.4
21 silly currentTree +-- minimist@1.2.0
21 silly currentTree +-- moment@2.17.1
21 silly currentTree +-- nbdime@0.4.0
21 silly currentTree | +-- @jupyterlab/apputils@0.8.2
21 silly currentTree | | `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree | +-- @jupyterlab/codeeditor@0.8.1
21 silly currentTree | | `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree | +-- @jupyterlab/codemirror@0.8.1
21 silly currentTree | | `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree | +-- @jupyterlab/coreutils@0.7.1
21 silly currentTree | +-- @jupyterlab/outputarea@0.8.2
21 silly currentTree | | `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree | +-- @jupyterlab/rendermime-interfaces@0.2.1
21 silly currentTree | +-- @jupyterlab/rendermime@0.8.2
21 silly currentTree | | `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree | `-- @jupyterlab/services@0.47.1
21 silly currentTree |   `-- @jupyterlab/coreutils@0.8.1
21 silly currentTree +-- node-fetch@1.7.3
21 silly currentTree +-- number-is-nan@1.0.1
21 silly currentTree +-- object-assign@4.1.1
21 silly currentTree +-- once@1.4.0
21 silly currentTree +-- parchment@1.1.1
21 silly currentTree +-- path-is-absolute@1.0.1
21 silly currentTree +-- path-posix@1.0.0
21 silly currentTree +-- process-nextick-args@1.0.7
21 silly currentTree +-- promise@7.3.1
21 silly currentTree +-- prop-types@15.6.0
21 silly currentTree +-- querystringify@1.0.0
21 silly currentTree +-- quill-delta@3.6.2
21 silly currentTree +-- quill@1.3.4
21 silly currentTree +-- react-dom-factories@1.0.2
21 silly currentTree +-- react-dom@15.6.2
21 silly currentTree +-- react-quill@1.2.0
21 silly currentTree +-- react-toggle-display@2.2.0
21 silly currentTree +-- react-widgets@3.5.0
21 silly currentTree +-- react@15.6.2
21 silly currentTree +-- readable-stream@2.3.3
21 silly currentTree +-- requires-port@1.0.0
21 silly currentTree +-- rimraf@2.6.2
21 silly currentTree +-- safe-buffer@5.1.1
21 silly currentTree +-- sanitize-html@1.15.0
21 silly currentTree +-- setimmediate@1.0.5
21 silly currentTree +-- srcset@1.0.0
21 silly currentTree +-- string_decoder@1.0.3
21 silly currentTree +-- tslib@1.8.0
21 silly currentTree +-- typescript@2.4.2
21 silly currentTree +-- ua-parser-js@0.7.17
21 silly currentTree +-- uncontrollable@4.1.0
21 silly currentTree +-- url-parse@1.2.0
21 silly currentTree +-- util-deprecate@1.0.2
21 silly currentTree +-- warning@2.1.0
21 silly currentTree +-- whatwg-fetch@2.0.3
21 silly currentTree +-- wrappy@1.0.2
21 silly currentTree +-- xtend@4.0.1
21 silly currentTree `-- xterm@2.8.1
22 silly idealTree jupyterlab-git@0.1.0
22 silly idealTree +-- @angular/core@4.4.6
22 silly idealTree +-- @jupyterlab/application@0.10.0
22 silly idealTree +-- @jupyterlab/apputils@0.10.0
22 silly idealTree +-- @jupyterlab/cells@0.10.0
22 silly idealTree +-- @jupyterlab/codeeditor@0.10.0
22 silly idealTree +-- @jupyterlab/codemirror@0.10.0
22 silly idealTree +-- @jupyterlab/console@0.10.0
22 silly idealTree +-- @jupyterlab/coreutils@0.10.1
22 silly idealTree +-- @jupyterlab/docmanager@0.10.0
22 silly idealTree +-- @jupyterlab/docregistry@0.10.0
22 silly idealTree +-- @jupyterlab/filebrowser@0.10.0
22 silly idealTree +-- @jupyterlab/outputarea@0.10.0
22 silly idealTree +-- @jupyterlab/rendermime-interfaces@0.3.1
22 silly idealTree +-- @jupyterlab/rendermime@0.10.0
22 silly idealTree +-- @jupyterlab/services@0.49.0
22 silly idealTree +-- @jupyterlab/terminal@0.10.0
22 silly idealTree +-- @jupyterlab/theming@0.9.0
22 silly idealTree +-- @phosphor/algorithm@1.1.2
22 silly idealTree +-- @phosphor/application@1.5.0
22 silly idealTree +-- @phosphor/collections@1.1.2
22 silly idealTree +-- @phosphor/commands@1.4.0
22 silly idealTree +-- @phosphor/coreutils@1.3.0
22 silly idealTree +-- @phosphor/disposable@1.1.2
22 silly idealTree +-- @phosphor/domutils@1.1.2
22 silly idealTree +-- @phosphor/dragdrop@1.3.0
22 silly idealTree +-- @phosphor/keyboard@1.1.2
22 silly idealTree +-- @phosphor/messaging@1.2.2
22 silly idealTree +-- @phosphor/properties@1.1.2
22 silly idealTree +-- @phosphor/signaling@1.2.2
22 silly idealTree +-- @phosphor/virtualdom@1.1.2
22 silly idealTree +-- @phosphor/widgets@1.5.0
22 silly idealTree +-- @types/codemirror@0.0.38
22 silly idealTree +-- @types/marked@0.0.28
22 silly idealTree +-- @types/mathjax@0.0.31
22 silly idealTree +-- @types/quill@1.3.3
22 silly idealTree +-- @types/react-dom@15.5.6
22 silly idealTree | `-- @types/react@15.6.7
22 silly idealTree +-- @types/react@16.0.24
22 silly idealTree +-- @types/sanitize-html@1.14.0
22 silly idealTree +-- @types/text-encoding@0.0.30
22 silly idealTree +-- ajv@5.3.0
22 silly idealTree +-- ansi_up@1.3.0
22 silly idealTree +-- array-uniq@1.0.3
22 silly idealTree +-- asap@2.0.6
22 silly idealTree +-- balanced-match@1.0.0
22 silly idealTree +-- brace-expansion@1.1.8
22 silly idealTree +-- classnames@2.2.5
22 silly idealTree +-- clone@2.1.1
22 silly idealTree +-- co@4.6.0
22 silly idealTree +-- codemirror@5.31.0
22 silly idealTree +-- concat-map@0.0.1
22 silly idealTree +-- core-js@1.2.7
22 silly idealTree +-- core-util-is@1.0.2
22 silly idealTree +-- create-react-class@15.6.2
22 silly idealTree +-- date-arithmetic@3.1.0
22 silly idealTree +-- deconstruct-number-format@0.0.1
22 silly idealTree +-- deep-equal@1.0.1
22 silly idealTree +-- dom-helpers@2.4.0
22 silly idealTree +-- dom-serializer@0.1.0
22 silly idealTree | `-- domelementtype@1.1.3
22 silly idealTree +-- domelementtype@1.3.0
22 silly idealTree +-- domhandler@2.4.1
22 silly idealTree +-- domutils@1.6.2
22 silly idealTree +-- encoding@0.1.12
22 silly idealTree +-- entities@1.1.1
22 silly idealTree +-- eventemitter3@2.0.3
22 silly idealTree +-- extend@3.0.1
22 silly idealTree +-- fast-deep-equal@1.0.0
22 silly idealTree +-- fast-diff@1.1.2
22 silly idealTree +-- fast-json-stable-stringify@2.0.0
22 silly idealTree +-- fbjs@0.8.16
22 silly idealTree +-- format-number-with-string@0.0.2
22 silly idealTree +-- format-number@2.0.2
22 silly idealTree +-- fs.realpath@1.0.0
22 silly idealTree +-- glob@7.1.2
22 silly idealTree +-- htmlparser2@3.9.2
22 silly idealTree +-- iconv-lite@0.4.19
22 silly idealTree +-- inflight@1.0.6
22 silly idealTree +-- inherits@2.0.3
22 silly idealTree +-- invariant@2.2.2
22 silly idealTree +-- is-stream@1.1.0
22 silly idealTree +-- isarray@1.0.0
22 silly idealTree +-- isomorphic-fetch@2.2.1
22 silly idealTree +-- jquery@2.2.4
22 silly idealTree +-- js-tokens@3.0.2
22 silly idealTree +-- json-schema-traverse@0.3.1
22 silly idealTree +-- json-stable-stringify@1.0.1
22 silly idealTree +-- jsonify@0.0.0
22 silly idealTree +-- lodash.escaperegexp@4.1.2
22 silly idealTree +-- lodash@4.17.4
22 silly idealTree +-- loose-envify@1.3.1
22 silly idealTree +-- marked@0.3.6
22 silly idealTree +-- minimatch@3.0.4
22 silly idealTree +-- minimist@1.2.0
22 silly idealTree +-- moment@2.17.1
22 silly idealTree +-- nbdime@0.4.0
22 silly idealTree | +-- @jupyterlab/apputils@0.8.2
22 silly idealTree | | `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree | +-- @jupyterlab/codeeditor@0.8.1
22 silly idealTree | | `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree | +-- @jupyterlab/codemirror@0.8.1
22 silly idealTree | | `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree | +-- @jupyterlab/coreutils@0.7.1
22 silly idealTree | +-- @jupyterlab/outputarea@0.8.2
22 silly idealTree | | `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree | +-- @jupyterlab/rendermime-interfaces@0.2.1
22 silly idealTree | +-- @jupyterlab/rendermime@0.8.2
22 silly idealTree | | `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree | `-- @jupyterlab/services@0.47.1
22 silly idealTree |   `-- @jupyterlab/coreutils@0.8.1
22 silly idealTree +-- node-fetch@1.7.3
22 silly idealTree +-- number-is-nan@1.0.1
22 silly idealTree +-- object-assign@4.1.1
22 silly idealTree +-- once@1.4.0
22 silly idealTree +-- parchment@1.1.1
22 silly idealTree +-- path-is-absolute@1.0.1
22 silly idealTree +-- path-posix@1.0.0
22 silly idealTree +-- process-nextick-args@1.0.7
22 silly idealTree +-- promise@7.3.1
22 silly idealTree +-- prop-types@15.6.0
22 silly idealTree +-- querystringify@1.0.0
22 silly idealTree +-- quill-delta@3.6.2
22 silly idealTree +-- quill@1.3.4
22 silly idealTree +-- react-dom-factories@1.0.2
22 silly idealTree +-- react-dom@15.6.2
22 silly idealTree +-- react-quill@1.2.0
22 silly idealTree +-- react-toggle-display@2.2.0
22 silly idealTree +-- react-widgets@3.5.0
22 silly idealTree +-- react@15.6.2
22 silly idealTree +-- readable-stream@2.3.3
22 silly idealTree +-- requires-port@1.0.0
22 silly idealTree +-- rimraf@2.6.2
22 silly idealTree +-- safe-buffer@5.1.1
22 silly idealTree +-- sanitize-html@1.15.0
22 silly idealTree +-- setimmediate@1.0.5
22 silly idealTree +-- srcset@1.0.0
22 silly idealTree +-- string_decoder@1.0.3
22 silly idealTree +-- tslib@1.8.0
22 silly idealTree +-- typescript@2.4.2
22 silly idealTree +-- ua-parser-js@0.7.17
22 silly idealTree +-- uncontrollable@4.1.0
22 silly idealTree +-- url-parse@1.2.0
22 silly idealTree +-- util-deprecate@1.0.2
22 silly idealTree +-- warning@2.1.0
22 silly idealTree +-- whatwg-fetch@2.0.3
22 silly idealTree +-- wrappy@1.0.2
22 silly idealTree +-- xtend@4.0.1
22 silly idealTree `-- xterm@2.8.1
23 silly generateActionsToTake Starting
24 silly install generateActionsToTake
25 silly generateActionsToTake Finishing
26 silly diffTrees action count 0
27 silly decomposeActions action count 0
28 silly runTopLevelLifecycles Starting
29 silly install runPreinstallTopLevelLifecycles
30 silly preinstall jupyterlab-git@0.1.0 C:\Users\G30622\miniconda3\jupyterlab-git-master\jupyterlab-git-2586e21a
31 info lifecycle jupyterlab-git@0.1.0~preinstall: jupyterlab-git@0.1.0
32 silly lifecycle jupyterlab-git@0.1.0~preinstall: no script for preinstall, continuing
33 silly executeActions Starting
34 silly install executeActions
35 silly doSerial global-install 0
36 silly doParallel fetch 0
37 verbose correctMkdir C:\Users\G30622\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
38 verbose lock using C:\Users\G30622\AppData\Roaming\npm-cache\_locks\staging-7f6b73751b3f9cd8.lock for C:\Users\G30622\miniconda3\jupyterlab-git-master\node_modules\.staging
39 silly doParallel extract 0
40 silly doParallel preinstall 0
41 silly doReverseSerial remove 0
42 silly doSerial move 0
43 silly doSerial finalize 0
44 silly doSerial build 0
45 silly doSerial global-link 0
46 silly doParallel update-linked 0
47 silly doSerial install 0
48 silly doSerial postinstall 0
49 verbose unlock done using C:\Users\G30622\AppData\Roaming\npm-cache\_locks\staging-7f6b73751b3f9cd8.lock for C:\Users\G30622\miniconda3\jupyterlab-git-master\node_modules\.staging
50 silly executeActions Finishing
51 silly rollbackFailedOptional Starting
52 silly rollbackFailedOptional Finishing
53 silly install runPostinstallTopLevelLifecycles
54 silly build jupyterlab-git@0.1.0
55 info linkStuff jupyterlab-git@0.1.0
56 silly linkStuff jupyterlab-git@0.1.0 has C:\Users\G30622\miniconda3 as its parent node_modules
57 verbose linkBins jupyterlab-git@0.1.0
58 verbose linkMans jupyterlab-git@0.1.0
59 silly install jupyterlab-git@0.1.0 C:\Users\G30622\miniconda3\jupyterlab-git-master\jupyterlab-git-2586e21a
60 info lifecycle jupyterlab-git@0.1.0~install: jupyterlab-git@0.1.0
61 silly lifecycle jupyterlab-git@0.1.0~install: no script for install, continuing
62 silly postinstall jupyterlab-git@0.1.0 C:\Users\G30622\miniconda3\jupyterlab-git-master\jupyterlab-git-2586e21a
63 info lifecycle jupyterlab-git@0.1.0~postinstall: jupyterlab-git@0.1.0
64 silly lifecycle jupyterlab-git@0.1.0~postinstall: no script for postinstall, continuing
65 silly prepublish jupyterlab-git@0.1.0 C:\Users\G30622\miniconda3\jupyterlab-git-master\jupyterlab-git-2586e21a
66 info lifecycle jupyterlab-git@0.1.0~prepublish: jupyterlab-git@0.1.0
67 verbose lifecycle jupyterlab-git@0.1.0~prepublish: unsafe-perm in lifecycle true
68 verbose lifecycle jupyterlab-git@0.1.0~prepublish: PATH: C:\Users\G30622\miniconda3\node_modules\npm\bin\node-gyp-bin;C:\Users\G30622\miniconda3\jupyterlab-git-master\node_modules\.bin;C:\Users\G30622\miniconda3;C:\Users\G30622\miniconda3\Library\mingw-w64\bin;C:\Users\G30622\miniconda3\Library\usr\bin;C:\Users\G30622\miniconda3\Library\bin;C:\Users\G30622\miniconda3\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Interactive Intelligence\ININ Trace Initialization\;C:\Program Files (x86)\Interactive Intelligence\ICUserApps\;C:\Program Files\Interactive Intelligence\ICUserApps\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
69 verbose lifecycle jupyterlab-git@0.1.0~prepublish: CWD: C:\Users\G30622\miniconda3\jupyterlab-git-master
70 silly lifecycle jupyterlab-git@0.1.0~prepublish: Args: [ '/d /s /c', 'npm run build' ]
71 silly lifecycle jupyterlab-git@0.1.0~prepublish: Returned: code: 1  signal: null
72 info lifecycle jupyterlab-git@0.1.0~prepublish: Failed to exec prepublish script
73 warn @angular/core@4.4.6 requires a peer of rxjs@^5.0.1 but none was installed.
74 verbose If you need help, you may report this error at:
74 verbose     <https://github.com/npm/npm/issues>
75 warn @angular/core@4.4.6 requires a peer of zone.js@^0.8.4 but none was installed.
76 verbose If you need help, you may report this error at:
76 verbose     <https://github.com/npm/npm/issues>
77 verbose stack Error: jupyterlab-git@0.1.0 prepublish: `npm run build`
77 verbose stack Exit status 1
77 verbose stack     at EventEmitter.<anonymous> (C:\Users\G30622\miniconda3\node_modules\npm\lib\utils\lifecycle.js:255:16)
77 verbose stack     at emitTwo (events.js:106:13)
77 verbose stack     at EventEmitter.emit (events.js:191:7)
77 verbose stack     at ChildProcess.<anonymous> (C:\Users\G30622\miniconda3\node_modules\npm\lib\utils\spawn.js:40:14)
77 verbose stack     at emitTwo (events.js:106:13)
77 verbose stack     at ChildProcess.emit (events.js:191:7)
77 verbose stack     at maybeClose (internal/child_process.js:886:16)
77 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
78 verbose pkgid jupyterlab-git@0.1.0
79 verbose cwd C:\Users\G30622\miniconda3\jupyterlab-git-master
80 error Windows_NT 6.1.7601
81 error argv "C:\\Users\\G30622\\miniconda3\\Library\\bin\\node.exe" "C:\\Users\\G30622\\miniconda3\\node_modules\\npm\\bin\\npm-cli.js" "install"
82 error node v6.10.3
83 error npm  v3.10.10
84 error code ELIFECYCLE
85 error jupyterlab-git@0.1.0 prepublish: `npm run build`
85 error Exit status 1
86 error Failed at the jupyterlab-git@0.1.0 prepublish script 'npm run build'.
86 error Make sure you have the latest version of node.js and npm installed.
86 error If you do, this is most likely a problem with the jupyterlab-git package,
86 error not with npm itself.
86 error Tell the author that this fails on your system:
86 error     npm run build
86 error You can get information on how to open an issue for this project with:
86 error     npm bugs jupyterlab-git
86 error Or if that isn't available, you can get their info via:
86 error     npm owner ls jupyterlab-git
86 error There is likely additional logging output above.
87 verbose exit [ 1, true ]

```

**Comment by zzhangjii** [comment]
Sorry, I just found the package has conflicts with the most recent release of jupyterlab 0.29.2;
Conflicts seem like come from react component.
I'm trying to find the problem and fix it.

**Comment by yougha54** [comment]
Hi, thanks for the responsiveness,
I switch to jupyter lab 0.27 and I still have the same pb

**Comment by zzhangjii** [comment]
It turns out to be conflict ways of react type declaration in previous versions. 
Simple way to fix it is first delete these two lines in package.json
    "@types/react": "^16.0.0",
    "@types/react-dom": "^15.5.2",
And update these to new versions: 
    "@jupyterlab/application": "^0.12.0",
    "@jupyterlab/apputils": "^0.12.4",
    "@jupyterlab/console": "^0.12.0",
    "@jupyterlab/filebrowser": "^0.12.1",
    "@jupyterlab/terminal": "^0.12.0",

Then it should work fine with jupyterlab version 0.29.2
I'll upload the fixed package.json tomorrow.

**Comment by yougha54** [comment]
that works pretty well,
thanks
