### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by hadim** [jupyterlab/jupyterlab-git#194]
I tried to install it using the recently added `jupyterlab_manager` extension in the last JLab 0.33.

The error is:

```
[1/4] Resolving packages...
⠂ @jupyterlab/cells@^0.17.2[I 14:54:58.309 LabApp] Adapting to protocol v5.1 for kernel e31b61e1-ed99-45f7-b7bb-20c058181f64
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 28.64s.
[I 14:55:23.943 LabApp] > node /home/hadim/local/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve './images/clear-white.svg' in '/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style'
    at factory.create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:2817:7
    at /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:393:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at fs.stat (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at process.nextTick (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:176:11)
resolve './images/clear-white.svg' in '/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style'
  using description file: /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/package.json (relative path: ./style/images/clear-white.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.json doesn't exist
      as directory
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

My config:

```bash
$ conda list |grep jupyter
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.33.0                   py36_0    conda-forge
jupyterlab-launcher       0.11.2                    <pip>
jupyterlab_launcher       0.11.2                     py_0    conda-forge
$ yarn --version
1.8.0
$ node --version
v9.11.1
$ conda info

     active environment : None
       user config file : /home/hadim/.condarc
 populated config files : /home/hadim/.condarc
          conda version : 4.5.8
    conda-build version : 3.11.0
         python version : 3.6.6.final.0
       base environment : /home/hadim/local/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/hadim/local/conda/pkgs
                          /home/hadim/.conda/pkgs
       envs directories : /home/hadim/local/conda/envs
                          /home/hadim/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.6 Linux/4.15.0-29-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False 
```

**Comment by NoahStapp** [comment]
Hey,

Can you describe what steps you took to install the extension? I tried to reproduce this issue with the extension manager but couldn't successfully reproduce it.

**Comment by hadim** [comment]
- Fire JLab
- Search for `git` in the Extension pane search bar.
- Click install.
- A message appears asking to rebuild.
- Click rebuild.
- After less than a minute, the error message (see my first post) appears.
- In the meantime, Jlab shows the `Build Complete` window and as me to reload the page.
- After clicking `Reload`, a new window appears asking to build the `@jupyterlab/git` extension (I guess JLab asks for a rebuild because the one before failed).
- Clicking rebuild shows the same error message.

**Comment by NoahStapp** [comment]
I can't reproduce that error, is your git extension's version 0.1.1? There was an updated version early this morning, does that fix the issue?

**Comment by ashwinvis** [comment]
I also get the same error with a fresh install. See the terminal log below.

[error_log.txt](https://github.com/jupyterlab/jupyterlab-git/files/2245987/error_log.txt)

Also notice that I **have to** start from `yarn` instead of `npm install` as the latter throws an error.

**Comment by hadim** [comment]
I just tried to install it from the command line with `jupyter labextension install @jupyterlab/git` and got the same error:

```
$ jupyter labextension install @jupyterlab/git
> /home/hadim/local/conda/bin/npm pack @jupyterlab/git
npm notice 
npm notice 📦  @jupyterlab/git@0.1.2
npm notice === Tarball Contents === 
npm notice 1.5kB  package.json                                       
npm notice 1.5kB  LICENSE                                            
npm notice 1.5kB  README.md                                          
npm notice 984B   lib/components_style/BranchHeaderStyle.d.ts        
npm notice 3.8kB  lib/components_style/BranchHeaderStyle.js          
npm notice 923B   lib/components_style/FileItemStyle.d.ts            
npm notice 2.9kB  lib/components_style/FileItemStyle.js              
npm notice 1.5kB  lib/components_style/FileListStyle.d.ts            
npm notice 3.2kB  lib/components_style/FileListStyle.js              
npm notice 250B   lib/components_style/GitPanelStyle.d.ts            
npm notice 805B   lib/components_style/GitPanelStyle.js              
npm notice 538B   lib/components_style/GitStageStyle.d.ts            
npm notice 2.4kB  lib/components_style/GitStageStyle.js              
npm notice 45B    lib/components_style/GitWidgetStyle.d.ts           
npm notice 363B   lib/components_style/GitWidgetStyle.js             
npm notice 108B   lib/components_style/HistorySideBarStyle.d.ts      
npm notice 815B   lib/components_style/HistorySideBarStyle.js        
npm notice 297B   lib/components_style/NewBranchBoxStyle.d.ts        
npm notice 1.2kB  lib/components_style/NewBranchBoxStyle.js          
npm notice 445B   lib/components_style/PastCommitNodeStyle.d.ts      
npm notice 1.3kB  lib/components_style/PastCommitNodeStyle.js        
npm notice 56B    lib/components_style/PastCommitsStyle.d.ts         
npm notice 203B   lib/components_style/PastCommitsStyle.js           
npm notice 317B   lib/components_style/PathHeaderStyle.d.ts          
npm notice 2.0kB  lib/components_style/PathHeaderStyle.js            
npm notice 852B   lib/components_style/SinglePastCommitInfoStyle.d.ts
npm notice 2.8kB  lib/components_style/SinglePastCommitInfoStyle.js  
npm notice 1.1kB  lib/components/BranchHeader.d.ts                   
npm notice 5.5kB  lib/components/BranchHeader.js                     
npm notice 741B   lib/components/CommitBox.d.ts                      
npm notice 2.4kB  lib/components/CommitBox.js                        
npm notice 1.3kB  lib/components/FileItem.d.ts                       
npm notice 7.8kB  lib/components/FileItem.js                         
npm notice 3.8kB  lib/components/FileList.d.ts                       
npm notice 19.7kB lib/components/FileList.js                         
npm notice 1.5kB  lib/components/GitPanel.d.ts                       
npm notice 11.4kB lib/components/GitPanel.js                         
npm notice 1.3kB  lib/components/GitStage.d.ts                       
npm notice 4.8kB  lib/components/GitStage.js                         
npm notice 2.9kB  lib/components/GitWidget.d.ts                      
npm notice 3.9kB  lib/components/GitWidget.js                        
npm notice 694B   lib/components/HistorySideBar.d.ts                 
npm notice 1.8kB  lib/components/HistorySideBar.js                   
npm notice 546B   lib/components/NewBranchBox.d.ts                   
npm notice 1.7kB  lib/components/NewBranchBox.js                     
npm notice 637B   lib/components/PastCommitNode.d.ts                 
npm notice 2.8kB  lib/components/PastCommitNode.js                   
npm notice 833B   lib/components/PastCommits.d.ts                    
npm notice 1.4kB  lib/components/PastCommits.js                      
npm notice 395B   lib/components/PathHeader.d.ts                     
npm notice 1.3kB  lib/components/PathHeader.js                       
npm notice 612B   lib/components/SinglePastCommitInfo.d.ts           
npm notice 3.8kB  lib/components/SinglePastCommitInfo.js             
npm notice 594B   lib/git_mainmenu_command.d.ts                      
npm notice 5.6kB  lib/git_mainmenu_command.js                        
npm notice 4.8kB  lib/git.d.ts                                       
npm notice 9.5kB  lib/git.js                                         
npm notice 1.2kB  lib/index.d.ts                                     
npm notice 3.3kB  lib/index.js                                       
npm notice 386B   style/Images/arrow-down.svg                        
npm notice 3.9kB  style/Images/author.svg                            
npm notice 4.7kB  style/Images/branch.svg                            
npm notice 601B   style/Images/caretdownwhite.svg                    
npm notice 621B   style/Images/caretrightwhite.svg                   
npm notice 215B   style/Images/checkmark-icon.svg                    
npm notice 266B   style/Images/clear-white.svg                       
npm notice 3.9kB  style/Images/deletion-color.svg                    
npm notice 3.9kB  style/Images/deletion-white.svg                    
npm notice 289B   style/Images/deletions-made-icon.svg               
npm notice 4.4kB  style/Images/directory-white.svg                   
npm notice 4.4kB  style/Images/directory.svg                         
npm notice 242B   style/Images/discard-selected.svg                  
npm notice 242B   style/Images/discard.svg                           
npm notice 2.7kB  style/Images/edit-circle-active.svg                
npm notice 2.7kB  style/Images/edit-circle-selected-active.svg       
npm notice 2.7kB  style/Images/edit-circle-selected.svg              
npm notice 2.7kB  style/Images/edit-circle.svg                       
npm notice 841B   style/Images/fade-left.svg                         
npm notice 836B   style/Images/fade-right.svg                        
npm notice 767B   style/Images/head-circle-active.svg                
npm notice 767B   style/Images/head-circle-selected-active.svg       
npm notice 766B   style/Images/head-circle-selected.svg              
npm notice 766B   style/Images/head-circle.svg                       
npm notice 469B   style/Images/home.svg                              
npm notice 308B   style/Images/insertions-made-icon.svg              
npm notice 1.8kB  style/Images/left-arrow.svg                        
npm notice 173B   style/Images/move-file-down-hover.svg              
npm notice 175B   style/Images/move-file-down.svg                    
npm notice 170B   style/Images/move-file-up-hover.svg                
npm notice 169B   style/Images/move-file-up.svg                      
npm notice 681B   style/Images/normal-circle-active.svg              
npm notice 760B   style/Images/normal-circle-selected-active.svg     
npm notice 674B   style/Images/normal-circle-selected.svg            
npm notice 595B   style/Images/normal-circle.svg                     
npm notice 481B   style/Images/path-arrow-right.svg                  
npm notice 200B   style/Images/plus-white.svg                        
npm notice 185B   style/Images/plus.svg                              
npm notice 4.0kB  style/Images/refresh-hover.svg                     
npm notice 4.0kB  style/Images/refresh.svg                           
npm notice 3.9kB  style/Images/reset-white.svg                       
npm notice 3.9kB  style/Images/reset.svg                             
npm notice 1.8kB  style/Images/right-arrow.svg                       
npm notice 8.6kB  style/Images/track.svg                             
npm notice 4.4kB  style/Images/triangle-down-white.svg               
npm notice 3.8kB  style/Images/triangle-down.svg                     
npm notice 4.4kB  style/Images/triangle-right-white.svg              
npm notice 3.8kB  style/Images/triangle-right.svg                    
npm notice 1.4kB  style/variables.css                                
npm notice === Tarball Details === 
npm notice name:          @jupyterlab/git                         
npm notice version:       0.1.2                                   
npm notice filename:      jupyterlab-git-0.1.2.tgz                
npm notice package size:  34.5 kB                                 
npm notice unpacked size: 236.7 kB                                
npm notice shasum:        77892d1fe8e330346b48823de42bd4696e33161b
npm notice integrity:     sha512-007mX6nruPGyj[...]AV2LWD0hPdXCA==
npm notice total files:   108                                     
npm notice 
jupyterlab-git-0.1.2.tgz

"@jupyter-widgets/jupyterlab-manager@0.35.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=2.0.2 <3.0.0          >=1.1.0 <2.0.0   @jupyterlab/coreutils
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.17.3 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime
>=3.0.3 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services


> node /home/hadim/local/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
⠂ @jupyterlab/imageviewer-extension@^0.17.2
warning css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@jupyterlab/vdom-extension > @nteract/transform-vdom@1.1.1" has incorrect peer dependency "react@^15.6.1".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 27.04s.
> node /home/hadim/local/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve './images/clear-white.svg' in '/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style'
    at factory.create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:2817:7
    at /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/neo-async/async.js:6783:13
    at normalResolver.resolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:393:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
    at resolver.doResolve (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at hook.callAsync (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at fs.stat (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at process.nextTick (/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at process._tickCallback (internal/process/next_tick.js:176:11)
resolve './images/clear-white.svg' in '/home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style'
  using description file: /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/package.json (relative path: ./style)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/package.json (relative path: ./style/images/clear-white.svg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg.json doesn't exist
      as directory
        /home/hadim/local/conda/share/jupyter/lab/staging/node_modules/@jupyterlab/git/style/images/clear-white.svg doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by NoahStapp** [comment]
It looks like there was accidentally two image folders, one named "Images" and one named "images". 0.1.3 was just published, which removes the "Images" folder and moves all images into "images". Can you see if that fixed the issue?

**Comment by ashwinvis** [comment]
Works for me by installing from the git master version. Maybe @hadim can confirm the command line installation.

**Comment by hadim** [comment]
I confirm it now works even from the extension manager. Thanks. Awesome plugin by the way!

**Comment by NoahStapp** [comment]
Glad to hear it!

**Comment by dunjoye4real** [comment]
I have this same error, and my jupyter lab version is `v0.31.12`
terminal log below

`> /usr/bin/npm pack @jupyterlab/git
npm notice
npm notice 📦  @jupyterlab/git@0.1.3
npm notice === Tarball Contents ===
npm notice 1.5kB  package.json
npm notice 1.5kB  LICENSE
npm notice 1.5kB  README.md
npm notice 984B   lib/components_style/BranchHeaderStyle.d.ts
npm notice 3.8kB  lib/components_style/BranchHeaderStyle.js
npm notice 923B   lib/components_style/FileItemStyle.d.ts
npm notice 2.9kB  lib/components_style/FileItemStyle.js
npm notice 1.5kB  lib/components_style/FileListStyle.d.ts
npm notice 3.2kB  lib/components_style/FileListStyle.js
npm notice 250B   lib/components_style/GitPanelStyle.d.ts
npm notice 805B   lib/components_style/GitPanelStyle.js
npm notice 538B   lib/components_style/GitStageStyle.d.ts
npm notice 2.4kB  lib/components_style/GitStageStyle.js
npm notice 45B    lib/components_style/GitWidgetStyle.d.ts
npm notice 363B   lib/components_style/GitWidgetStyle.js
npm notice 108B   lib/components_style/HistorySideBarStyle.d.ts
npm notice 815B   lib/components_style/HistorySideBarStyle.js
npm notice 297B   lib/components_style/NewBranchBoxStyle.d.ts
npm notice 1.2kB  lib/components_style/NewBranchBoxStyle.js
npm notice 445B   lib/components_style/PastCommitNodeStyle.d.ts
npm notice 1.3kB  lib/components_style/PastCommitNodeStyle.js
npm notice 56B    lib/components_style/PastCommitsStyle.d.ts
npm notice 203B   lib/components_style/PastCommitsStyle.js
npm notice 317B   lib/components_style/PathHeaderStyle.d.ts
npm notice 2.0kB  lib/components_style/PathHeaderStyle.js
npm notice 852B   lib/components_style/SinglePastCommitInfoStyle.d.ts
npm notice 2.8kB  lib/components_style/SinglePastCommitInfoStyle.js
npm notice 1.1kB  lib/components/BranchHeader.d.ts
npm notice 5.5kB  lib/components/BranchHeader.js
npm notice 741B   lib/components/CommitBox.d.ts
npm notice 2.4kB  lib/components/CommitBox.js
npm notice 1.3kB  lib/components/FileItem.d.ts
npm notice 7.8kB  lib/components/FileItem.js
npm notice 3.8kB  lib/components/FileList.d.ts
npm notice 19.7kB lib/components/FileList.js
npm notice 1.5kB  lib/components/GitPanel.d.ts
npm notice 11.4kB lib/components/GitPanel.js
npm notice 1.3kB  lib/components/GitStage.d.ts
npm notice 4.8kB  lib/components/GitStage.js
npm notice 2.9kB  lib/components/GitWidget.d.ts
npm notice 3.9kB  lib/components/GitWidget.js
npm notice 694B   lib/components/HistorySideBar.d.ts
npm notice 1.8kB  lib/components/HistorySideBar.js
npm notice 546B   lib/components/NewBranchBox.d.ts
npm notice 1.7kB  lib/components/NewBranchBox.js
npm notice 637B   lib/components/PastCommitNode.d.ts
npm notice 2.8kB  lib/components/PastCommitNode.js
npm notice 833B   lib/components/PastCommits.d.ts
npm notice 1.4kB  lib/components/PastCommits.js
npm notice 395B   lib/components/PathHeader.d.ts
npm notice 1.3kB  lib/components/PathHeader.js
npm notice 612B   lib/components/SinglePastCommitInfo.d.ts
npm notice 3.8kB  lib/components/SinglePastCommitInfo.js
npm notice 594B   lib/git_mainmenu_command.d.ts
npm notice 5.6kB  lib/git_mainmenu_command.js
npm notice 4.8kB  lib/git.d.ts
npm notice 9.5kB  lib/git.js
npm notice 1.2kB  lib/index.d.ts
npm notice 3.3kB  lib/index.js
npm notice 386B   style/images/arrow-down.svg
npm notice 3.9kB  style/images/author.svg
npm notice 4.7kB  style/images/branch.svg
npm notice 601B   style/images/caretdownwhite.svg
npm notice 621B   style/images/caretrightwhite.svg
npm notice 215B   style/images/checkmark-icon.svg
npm notice 266B   style/images/clear-white.svg
npm notice 3.9kB  style/images/deletion-color.svg
npm notice 3.9kB  style/images/deletion-white.svg
npm notice 289B   style/images/deletions-made-icon.svg
npm notice 4.4kB  style/images/directory-white.svg
npm notice 4.4kB  style/images/directory.svg
npm notice 242B   style/images/discard-selected.svg
npm notice 242B   style/images/discard.svg
npm notice 2.7kB  style/images/edit-circle-active.svg
npm notice 2.7kB  style/images/edit-circle-selected-active.svg
npm notice 2.7kB  style/images/edit-circle-selected.svg
npm notice 2.7kB  style/images/edit-circle.svg
npm notice 841B   style/images/fade-left.svg
npm notice 836B   style/images/fade-right.svg
npm notice 767B   style/images/head-circle-active.svg
npm notice 767B   style/images/head-circle-selected-active.svg
npm notice 766B   style/images/head-circle-selected.svg
npm notice 766B   style/images/head-circle.svg
npm notice 469B   style/images/home.svg
npm notice 308B   style/images/insertions-made-icon.svg
npm notice 1.8kB  style/images/left-arrow.svg
npm notice 173B   style/images/move-file-down-hover.svg
npm notice 175B   style/images/move-file-down.svg
npm notice 170B   style/images/move-file-up-hover.svg
npm notice 169B   style/images/move-file-up.svg
npm notice 681B   style/images/normal-circle-active.svg
npm notice 760B   style/images/normal-circle-selected-active.svg
npm notice 674B   style/images/normal-circle-selected.svg
npm notice 595B   style/images/normal-circle.svg
npm notice 481B   style/images/path-arrow-right.svg
npm notice 200B   style/images/plus-white.svg
npm notice 185B   style/images/plus.svg
npm notice 4.0kB  style/images/refresh-hover.svg
npm notice 4.0kB  style/images/refresh.svg
npm notice 3.9kB  style/images/reset-white.svg
npm notice 3.9kB  style/images/reset.svg
npm notice 1.8kB  style/images/right-arrow.svg
npm notice 8.6kB  style/images/track.svg
npm notice 4.4kB  style/images/triangle-down-white.svg
npm notice 3.8kB  style/images/triangle-down.svg
npm notice 4.4kB  style/images/triangle-right-white.svg
npm notice 3.8kB  style/images/triangle-right.svg
npm notice 1.4kB  style/variables.css
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/git
npm notice version:       0.1.3
npm notice filename:      jupyterlab-git-0.1.3.tgz
npm notice package size:  34.5 kB
npm notice unpacked size: 236.7 kB
npm notice shasum:        3649b04044cb11cdc887a29393587dcdc236d3fc
npm notice integrity:     sha512-ltVZwEv0D3Ie3[...]1wPBQ/V3EA53g==
npm notice total files:   108
npm notice
jupyterlab-git-0.1.3.tgz

Errored, use --debug for full output:
ValueError:
"@jupyterlab/git@0.1.3" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension            Package
>=0.15.4-0 <0.16.0-0    >=0.17.2-0 <0.18.0-0 @jupyterlab/application
>=0.15.5-0 <0.16.0-0    >=0.17.2-0 <0.18.0-0 @jupyterlab/apputils
>=0.15.4-0 <0.16.0-0    >=0.17.2-0 <0.18.0-0 @jupyterlab/console
>=1.0.10-0 <2.0.0-0     >=2.0.2-0 <3.0.0-0   @jupyterlab/coreutils
>=0.15.4-0 <0.16.0-0    >=0.17.3-0 <0.18.0-0 @jupyterlab/filebrowser
>=0.15.4-0 <0.16.0-0    >=0.17.2-0 <0.18.0-0 @jupyterlab/terminal`

**Comment by ashwinvis** [comment]
Upgrade your jupyterlab.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by dunjoye4real** [comment]
@ashwinvis Thanks. That worked for me
