### ISSUE TITLE
Installation fails, cannot find '@jupyterlab\git\package.json'

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab-git#203]
Hello,

I was trying to test this neat-looking extension out, but my installation failed. With 
`jupyter labextension install @jupyterlab/git`
I get the long error message below, but the key lines seem to be 
`error Received malformed response from registry for undefined. The registry may be down.`
and
`Error: Cannot find module '@jupyterlab\git\package.json'`

```
PS C:\Users\My-Name> jupyter lab --version  
0.33.4  
PS C:\Users\Regal-Lab> jupyter --version  
4.4.0
```

Any ideas? The full output is below.

```
PS C:\Users\My-Name> jupyter labextension install @jupyterlab/git
> C:\ProgramData\Anaconda3\npm.CMD pack @jupyterlab/git
jupyterlab-git-0.1.3.tgz

"jupyterlab-toc@0.2.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.2 <0.17.0 @jupyterlab/apputils
>=2.0.2 <3.0.0          >=1.0.0 <2.0.0   @jupyterlab/coreutils
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/docmanager
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/fileeditor
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=0.17.3 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/rendermime


> node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
error Received malformed response from registry for undefined. The registry may be down.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> node C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.6.0
$ webpack --config webpack.prod.config.js
C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error: Cannot find module '@jupyterlab\git\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.require.resolve (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:162:23
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:29:45
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:28:22)
    at Object.<anonymous> (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\webpack.config.js:20:7)
    at Module._compile (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\webpack.prod.config.js:3:14)
    at Module._compile (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\yargs\yargs.js:563:18)
    at C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\ProgramData\Anaconda3\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by aquirdTurtle** [comment]
Never mind, on repeated builds it seems to have fixed itself and is now working. Sorry for the spam.
