### ISSUE TITLE
Install cannot find package.json

### ISSUE THREAD

**Issue by mschroen** [jupyterlab/jupyterlab-git#290]
Trying to install this extension. The README.md seems to offer several (unrelated?) approaches. The following two commands worked fine, but had no effect on the jupyter lab GUI (i.e., no Git tab):
- `pip install jupyterlab-git`
- `jupyter serverextension enable --py jupyterlab_git`

So I guess I also have to install the labextension via
- `jupyter labextension install @jupyterlab/git`
 
However, this leads to the same problem as was presented in <https://github.com/jupyterlab/jupyterlab-git/issues/203>: Building jupyter lab fails. But the issue was closed without showing a solution. I also tried repeated execution of `jupyter lab build` but it has not solved the problem.
I am on Windows 7, Python 3.6.0, Jupyter 4.4.0, JupyterLab 0.33.4 .

```
$ jupyter labextension install @jupyterlab/git
> "C:\Program Files\nodejs\npm.CMD" pack @jupyterlab/git
npm notice
npm notice package: @jupyterlab/git@0.5.0
npm notice === Tarball Contents ===
npm notice 2.1kB  package.json
[...many more npm notices of such kind...]
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/git
npm notice version:       0.5.0
npm notice filename:      jupyterlab-git-0.5.0.tgz
npm notice package size:  43.5 kB
npm notice unpacked size: 281.9 kB
npm notice shasum:        0bcc3a59e316df106c7c1c2a957c3aece305f0e3
npm notice integrity:     sha512-pZBw7GWOWkr6H[...]2OxhgBQufq80Q==
npm notice total files:   125
npm notice
jupyterlab-git-0.5.0.tgz
Incompatible extension:

"@jupyterlab/git@0.5.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/console
>=0.17.3 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/filebrowser
>=0.17.2 <0.18.0        >=0.19.1 <0.20.0 @jupyterlab/terminal

Found compatible version: 0.1.3
> "C:\Program Files\nodejs\npm.CMD" pack @jupyterlab/git@0.1.3
npm notice
npm notice package: @jupyterlab/git@0.1.3
npm notice === Tarball Contents ===
npm notice 1.5kB  package.json
[...many more npm notices of such kind...]
npm notice === Tarball Details ===
npm notice name:          @jupyterlab/git
npm notice version:       0.1.3
npm notice filename:      jupyterlab-git-0.1.3.tgz
npm notice package size:  34.5 kB
npm notice unpacked size: 236.7 kB
npm notice shasum:        3649b04044cb11cdc887a29393587dcdc236d3fc
npm notice integrity:     sha512-ltVZwEv0D3Ie3[...]1wPBQ/V3EA53g==
npm notice total files:   108
npm notice
jupyterlab-git-0.1.3.tgz
> node c:\python\lib\site-packages\jupyterlab\staging\yarn.js install
yarn install v1.6.0
(node:5536) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info No lockfile found.
[1/4] Resolving packages...
> node c:\python\lib\site-packages\jupyterlab\staging\yarn.js run build:prod
yarn run v1.6.0
(node:6564) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
$ webpack --config webpack.prod.config.js
c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error: Cannot find module '@jupyterlab\git\package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.require.resolve (c:\python\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:162:23)
    at c:\python\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:29:45
    at Array.forEach (<anonymous>)
    at Object.ensureAssets (c:\python\share\jupyter\lab\staging\node_modules\@jupyterlab\buildutils\lib\build.js:28:22)
    at Object.<anonymous> (c:\python\share\jupyter\lab\staging\webpack.config.js:20:7)
    at Module._compile (c:\python\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (c:\python\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (c:\python\share\jupyter\lab\staging\webpack.prod.config.js:3:14)
    at Module._compile (c:\python\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:178:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (c:\python\share\jupyter\lab\staging\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse (c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (c:\python\share\jupyter\lab\staging\node_modules\yargs\yargs.js:567:18)
    at c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (c:\python\share\jupyter\lab\staging\node_modules\webpack-cli\bin\cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mschroen** [comment]
Nevermind, **upgrading jupyter lab** version from `0.33.4` to `0.35.4` did the trick. Works like a charm, thank you!
