### ISSUE TITLE
Push / Pull failing with no message

### ISSUE THREAD

**Issue by aquirdTurtle** [jupyterlab/jupyterlab-git#359]
I just updated to version 0.5.0 and was happy to see the new pull and push handling, but it's not working for me for some reason. 

![image](https://user-images.githubusercontent.com/4393192/58981427-987e5500-878f-11e9-9326-28d26ceb546e.png)
![image](https://user-images.githubusercontent.com/4393192/58981451-a7650780-878f-11e9-88fc-a07768f62c68.png)

`git pull` and `git push` both work fine in the terminal.

**Comment by jaipreet-s** [comment]
Could you provide a few more details

- The logs from the Jupyter server (They should have an error stack trace but looks like the UI is not bubbling that up)
- Your currently configured remotes (`git remote -v`)

**Comment by aquirdTurtle** [comment]
```
PS C:\Users\...> git remote -v
github  https://github.com/omarkb93/Data-Analysis-Code.git (fetch)
github  https://github.com/omarkb93/Data-Analysis-Code.git (push)
```
Not sure if this is quite what you mean by the logs from the server, but if I start up jupyter lab and then try a push then a pull, the kernel deposits the following in powershell:
```
PS C:\Users\...> jupyter lab
[I 21:54:13.127 LabApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 21:54:13.145 LabApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 21:54:13.145 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
base_url: /
[('/git/show_top_level', <class 'jupyterlab_git.handlers.Git_show_top_level_handler'>), ('/git/show_prefix', <class 'jupyterlab_git.handlers.Git_show_prefix_handler'>), ('/git/add', <class 'jupyterlab_git.handlers.Git_add_handler'>), ('/git/status', <class 'jupyterlab_git.handlers.Git_status_handler'>), ('/git/branch', <class 'jupyterlab_git.handlers.Git_branch_handler'>), ('/git/reset', <class 'jupyterlab_git.handlers.Git_reset_handler'>), ('/git/checkout', <class 'jupyterlab_git.handlers.Git_checkout_handler'>), ('/git/commit', <class 'jupyterlab_git.handlers.Git_commit_handler'>), ('/git/pull', <class 'jupyterlab_git.handlers.Git_pull_handler'>), ('/git/push', <class 'jupyterlab_git.handlers.Git_push_handler'>), ('/git/diff', <class 'jupyterlab_git.handlers.Git_diff_handler'>), ('/git/log', <class 'jupyterlab_git.handlers.Git_log_handler'>), ('/git/detailed_log', <class 'jupyterlab_git.handlers.Git_detailed_log_handler'>), ('/git/init', <class 'jupyterlab_git.handlers.Git_init_handler'>), ('/git/all_history', <class 'jupyterlab_git.handlers.Git_all_history_handler'>), ('/git/add_all_untracked', <class 'jupyterlab_git.handlers.Git_add_all_untracked_handler'>)]
[W 21:54:13.152 LabApp] JupyterLab server extension not enabled, manually loading...
[I 21:54:13.168 LabApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 21:54:13.169 LabApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 21:54:13.274 LabApp] Serving notebooks from local directory: C:\Users\Regal-Lab
[I 21:54:13.274 LabApp] 0 active kernels
[I 21:54:13.275 LabApp] The Jupyter Notebook is running at:
[I 21:54:13.275 LabApp] http://localhost:8888/?token=57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49
[I 21:54:13.275 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:54:13.281 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49&token=57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49
[I 21:54:13.377 LabApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 21:54:14.709 LabApp] Node v9.11.1

[W 21:54:14.787 LabApp] The extension "@jupyterlab/shortcutui" is outdated.

[I 21:54:14.974 LabApp] Build is up to date
[W 21:54:19.235 LabApp] 404 GET /metrics?1559793259218 (::1) 12.16ms referer=http://localhost:8888/lab
[E 21:54:25.546 LabApp] Uncaught exception POST /git/push?1559793265544 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/push?1559793265544', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Content-Length': '42', 'Authorization': 'token 57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49', 'Origin': 'http://localhost:8888', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36', 'Content-Type': 'application/json', 'Accept': '*/*', 'Referer': 'http://localhost:8888/lab', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9', 'Cookie': '_xsrf=2|6d023e70|06cb00e092b5fdc6735fe84518ed8f52|1558977838; username-localhost-8888="2|1:0|10:1559793265|23:username-localhost-8888|44:ZjgyOGZjZDE4YmJjNDRjMjkyMzgxYzJkYzdhYzUwNWE=|9aa1f7491cee67a60a10d81f1b51a8cd79ccd911830f8de79c22cff8ccd2cf48"'})
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab_git\handlers.py", line 312, in post
        origin = my_data["origin"]
    KeyError: 'origin'
[W 21:54:25.549 LabApp] Unhandled error
[E 21:54:25.549 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "42",
      "Authorization": "token 57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|6d023e70|06cb00e092b5fdc6735fe84518ed8f52|1558977838; username-localhost-8888=\"2|1:0|10:1559793265|23:username-localhost-8888|44:ZjgyOGZjZDE4YmJjNDRjMjkyMzgxYzJkYzdhYzUwNWE=|9aa1f7491cee67a60a10d81f1b51a8cd79ccd911830f8de79c22cff8ccd2cf48\""
    }
[E 21:54:25.550 LabApp] 500 POST /git/push?1559793265544 (::1) 4.01ms referer=http://localhost:8888/lab
[E 21:54:32.554 LabApp] Uncaught exception POST /git/pull?1559793272552 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/pull?1559793272552', version='HTTP/1.1', remote_ip='::1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Content-Length': '42', 'Authorization': 'token 57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49', 'Origin': 'http://localhost:8888', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36', 'Content-Type': 'application/json', 'Accept': '*/*', 'Referer': 'http://localhost:8888/lab', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9', 'Cookie': '_xsrf=2|6d023e70|06cb00e092b5fdc6735fe84518ed8f52|1558977838; username-localhost-8888="2|1:0|10:1559793265|23:username-localhost-8888|44:YWEwZjZkMDJiNjczNGVjYWJhYWJiYTU4NTViZDZmYjM=|5fbce029d79654461ab323d9a8365a381db3c6109908c7b814a0240025025f6f"'})
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab_git\handlers.py", line 292, in post
        origin = my_data["origin"]
    KeyError: 'origin'
[W 21:54:32.556 LabApp] Unhandled error
[E 21:54:32.557 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "42",
      "Authorization": "token 57fccaefa687d3d5f21f483b611a65a98dc39c8afff9bc49",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|6d023e70|06cb00e092b5fdc6735fe84518ed8f52|1558977838; username-localhost-8888=\"2|1:0|10:1559793265|23:username-localhost-8888|44:YWEwZjZkMDJiNjczNGVjYWJhYWJiYTU4NTViZDZmYjM=|5fbce029d79654461ab323d9a8365a381db3c6109908c7b814a0240025025f6f\""
    }
[E 21:54:32.557 LabApp] 500 POST /git/pull?1559793272552 (::1) 3.99ms referer=http://localhost:8888/lab
```

The `[E 21:54:25.546 LabApp] Uncaught exception POST /git/push?1559793265544 (::1)` and what follows is what appears after I do the push. Let me know if there's anything else I can provide.

**Comment by jaipreet-s** [comment]
Is the server extension up-to-date? From the `KeyError: 'origin'` error message it appears that the frontend is working with a older version of the server extension API

```
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```

**Comment by aquirdTurtle** [comment]
Hmm, okay some progress. After running the above commands I now get actual error messages, although it's still not working. I don't get any errors in powershell anymore. 

![image](https://user-images.githubusercontent.com/4393192/59052862-4f8cd600-884d-11e9-8b14-ff9cb0f32f32.png)
![image](https://user-images.githubusercontent.com/4393192/59052870-56b3e400-884d-11e9-92bc-28d3098705a4.png)

Looks like the command being run under the hood is getting garbled somehow. My first thought was that it might be an issue with the path name (e.g. having spaces) but the full path to my git repo looks pretty normal: 
C:\Users\Regal-Lab\Code\Data-Analysis-Code\.git

**Comment by jaipreet-s** [comment]
OK now this looks like the windows issue related to #356

**Comment by jaipreet-s** [comment]
Version 0.6 released with these changes

**Comment by aquirdTurtle** [comment]
Sorry, but I just updated to version 0.6 
```
PS C:\WINDOWS\system32> jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\share\jupyter\lab
        @jupyterlab/git v0.6.0 enabled  ok
        @jupyterlab/latex v0.6.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.2 enabled  ok
        @jupyterlab/shortcutui v0.3.1 enabled   X
        @jupyterlab/statusbar v0.5.0 enabled  ok
        @jupyterlab/toc v0.6.0 enabled  ok

   The following extension are outdated:
        @jupyterlab/shortcutui

   Consider running "jupyter labextension update --all" to check for updates.

PS C:\WINDOWS\system32>
```

and I still get the same errors:

![image](https://user-images.githubusercontent.com/4393192/59375357-2d8eca00-8d0b-11e9-9e81-e72243269647.png)
![image](https://user-images.githubusercontent.com/4393192/59375372-3a132280-8d0b-11e9-9c9d-be8509c92c42.png)

**Comment by jaipreet-s** [comment]
Is your serverextension on 0.6 as well?

**Comment by aquirdTurtle** [comment]
Okay, after redoing 
```
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```
it looks like it's working. Thanks! I must admit it's rather counterintuitive that `jupyter labextension update --all` doesn't manage this. I thought that was the 'correct' way to update extensions, and I can't find much documentation about this 'serverextension' counter part. I don't see servers mentioned anywhere on https://jupyterlab.readthedocs.io/en/stable/user/extensions.html. I see now that the three commands listed on the page for this extension
```
jupyter labextension install @jupyterlab/git
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
```
hint at needing to do more than usual, but since I installed a while ago I had forgotten about this. Perhaps an explicit instruction for how to update this extension on the readme for this extension could be helpful for future noobs like me.
