### ISSUE TITLE
Latest jupyterlab-git failed to run "jupyter serverextension enable --py jupyterlab_git --sys-prefix"

### ISSUE THREAD

**Issue by cyly** [jupyterlab/jupyterlab-git#373]
jupyter serverextension enable --py jupyterlab_git --sys-prefix
Traceback (most recent call last):
  File "/data/anaconda/envs/py35/bin/jupyter-serverextension", line 11, in <module>
    sys.exit(main())
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/jupyterlab_git/__init__.py", line 5, in <module>
    from jupyterlab_git.git import Git
  File "/data/anaconda/envs/py35/lib/python3.5/site-packages/jupyterlab_git/git.py", line 42
    cmd = ['git', 'diff', f'{single_commit}^!', '--name-only']
                                             ^
SyntaxError: invalid syntax

How to fix this issue? Is there any workaround? Or I miss some package?
This might be related with the commit of https://github.com/jupyterlab/jupyterlab-git/commit/f669aee24613563c4b8af28ba5fa06c847165ee4#diff-041cb4cfb7143f3bbcdd07d28dffa92c

Thank you very much!

**Comment by fcollonval** [comment]
Hey @cyly, the error comes from a f-string-format notation. This feature was introduced in Python 3.6.
A fix would be
```diff
- cmd = ['git', 'diff', f'{single_commit}^!', '--name-only']
+ cmd = ['git', 'diff', '{}^!'.format(single_commit), '--name-only']
```
But as there are maybe other case like that one, I recommend you to update to Python 3.6 or later if you can.

As jupyterlab supports Python>=3.5, this should definitely be corrected that.

**Comment by luispuerto** [comment]
I got similar error but I don't know why with python 2.7

```
jupyter serverextension enable --py jupyterlab_git
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-serverextension", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/site-packages/notebook/serverextensions.py", line 294, in start
    super(ServerExtensionApp, self).start()
  File "/usr/local/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/site-packages/notebook/serverextensions.py", line 211, in start
    self.toggle_server_extension_python(arg)
  File "/usr/local/lib/python2.7/site-packages/notebook/serverextensions.py", line 200, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/local/lib/python2.7/site-packages/notebook/serverextensions.py", line 328, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named jupyterlab_git
```

**Comment by fcollonval** [comment]
@luispuerto Python 2.7 support is dropped as it is no more supported by Jupyter.

But from the error it seems that the package `jupyterlab_git` is not installed on your system. Did you try installing the package through pip?

```bash
pip install jupyterlab_git
jupyter serverextension enable --py jupyterlab_git
```

**Comment by luispuerto** [comment]
I assure you that I've done that. I don't understand why it's on python 2.7 instead of 3.x

**Comment by luispuerto** [comment]
<img width="315" alt="Screen Shot 2019-07-10 at 13 03 31" src="https://user-images.githubusercontent.com/22882880/61000822-214e5a80-a313-11e9-9527-4f7d86452296.png">

**Comment by luispuerto** [comment]
as you can see here, jupyter is loading form 3.7

<img width="710" alt="Screen Shot 2019-07-10 at 13 04 33" src="https://user-images.githubusercontent.com/22882880/61000913-4fcc3580-a313-11e9-9979-012c12c935ea.png">

**Comment by fcollonval** [comment]
Ok you have unwanted interaction between two Python installations.

On unix, you could usually pick the python v3 using `python3` command. Then you can install the package in the right python using
```
python3 -m pip install jupyterlab-git
```

If you don't have such alias, you could also provide the full path something like `/usr/local/bin/python3.7` in your case I think.

**Comment by luispuerto** [comment]
I was able to finally make it work… I don't know how, but the error message still stands when I run 

```shell
jupyter serverextension enable --py jupyterlab_git
```

**Comment by fcollonval** [comment]
Good to hear that it is working for you @luispuerto. The error won't go as you have jupyter installed in both python installation (the 2.7 and the 3.7). So when you type `jupyter` in a console, the OS is looking in your `$PATH` for that executable. And it finds python 2.7 before python 3.7, so it uses the "wrong" python.

I advice you to read about virtual environment:
- with pip: https://docs.python.org/3/library/venv.html
- with conda: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
It will help you handling multiple python installation.
