### ISSUE TITLE
Commiting without having emailaddress set in global config results in an exception

### ISSUE THREAD

**Issue by nielstenboom** [jupyterlab/jupyterlab-git#396]
### The behavior you expected
When trying to do a commit without having previously run the command `git config --global user.email "you@example.com"` the commit should go through.

### The actual behavior (screenshots can be helpful here)
A fatal error occurs.

```
*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'ntboom@IT013385.(none)')
[E 13:50:52.317 LabApp] Uncaught exception POST /git/commit?1565610652291 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/git/commit?1565610652291', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/usr/local/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/jupyterlab_git/handlers.py", line 312, in post
        my_output = self.git.commit(commit_msg, top_repo_path)
      File "/usr/local/anaconda3/lib/python3.7/site-packages/jupyterlab_git/git.py", line 544, in commit
        ["git", "commit", "-m", commit_msg], cwd=top_repo_path
      File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 395, in check_output
        **kwargs).stdout
      File "/usr/local/anaconda3/lib/python3.7/subprocess.py", line 487, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'commit', '-m', 'Test commit']' returned non-zero exit status 128.
[W 13:50:52.342 LabApp] Unhandled error
[E 13:50:52.343 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "90",
      "Sec-Fetch-Mode": "cors",
      "Authorization": "token 02c3ee3f8dba48f9138df38ab00c619586b9036f53c894ce",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8888/lab/workspaces/test",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8,nl;q=0.7",
      "Cookie": "csrftoken=jJt3Ct4MwuhJmB18kaCsBw83uAV9VzIUgIFyhLt76G77YDuQfEUiyCZziRphlQlc; sessionid=tdghbf7fns1fimpirfr9cxmmpqsaem6s; _xsrf=2|394e2d49|f3761651851b3873b1f181a0da6b099e|1565610045; username-localhost-8888=\"2|1:0|10:1565610650|23:username-localhost-8888|44:ZGFlMTRmNDQxMjhhNGE3OTk4MDk4OWRjNjE4OGQ5OWM=|347c99c1399d75bba47b56ff3f4f28a4fc747d12be4c9f49738586670fdff75f\""
    }
[E 13:50:52.343 LabApp] 500 POST /git/commit?1565610652291 (::1) 49.05ms referer=http://localhost:8888/lab/workspaces/test
```

### How someone else could reproduce it
Do a commit in a git repository where;

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

are unset.

**Comment by jaipreet-s** [comment]
@fcollonval since he's closest to the code.

**Comment by fcollonval** [comment]
Hey @nielstenboom,
Are you using the latest 0.8.0 version of jupyterlab-git? If not could you please update your installation and test that the extension requests your identity before committing?

**Comment by nielstenboom** [comment]
Hi, thanks for the rapid response! 

I can confirm that I am on version 0.8.0 and that the extension does not request my identity when committing. The GUI just hangs and the commandline shows the exception I posted above after trying a commit.

I am on MacOS with a python 3.7.3 anaconda environment, with the following jupyter package versions: 
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.4.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==0.35.4
jupyterlab-git==0.8.0
jupyterlab-server==0.2.0

**Comment by fcollonval** [comment]
Ok, the trouble is that you are not using the latest jupyterlab version (1.0.x). So the latest webextension `@jupyterlab/git` cannot be installed.
Could you try the command `jupyter labextension list`? It should show you the version of `@jupyterlab/git` you are using. If this is not 0.8, you should update jupyterlab to 1.0.x (with pip or conda) and rebuild it to include the extensions (with `jupyter lab build`).

**Comment by nielstenboom** [comment]
Ah yes `jupyter labextension list` showed:

```$ jupyter labextension list
JupyterLab v0.35.4
Known labextensions:
   app dir: /usr/local/anaconda3/share/jupyter/lab
        @jupyterlab/git v0.6.0  enabled  OK
        nbdime-jupyterlab v1.0.0  enabled   X```

After updating jupyterlab to 1.0 and updating @jupyterlab/git to 0.8.0, I indeed got the popup to enter my name and email after committing!

Thank you for your quick response.
