### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ggosiang** [jupyterlab/jupyterlab-git#418]
trying to install from instruction, but got error in following step

**Install the server extension in development mode**
`pip install -e .`

error message,
```
ERROR: Command errored out with exit status 1:
     command: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jovyan/jupyterlab-git/setup.py'"'"'; __file__='"'"'/home/jovyan/jupyterlab-git/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/jovyan/jupyterlab-git/
    Complete output (28 lines):
    running develop
    running jsdeps
    `yarn` unavailable.  If you're running this command using sudo, make sure `yarn` is available to sudo
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jovyan/jupyterlab-git/setup.py", line 91, in <module>
        setuptools.setup(**setup_args)
      File "/opt/conda/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/opt/conda/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/jovyan/jupyterlab-git/setupbase.py", line 466, in run
        [self.run_command(cmd) for cmd in cmds]
      File "/home/jovyan/jupyterlab-git/setupbase.py", line 466, in <listcomp>
        [self.run_command(cmd) for cmd in cmds]
      File "/opt/conda/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/opt/conda/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/jovyan/jupyterlab-git/setupbase.py", line 262, in run
        c.run()
      File "/home/jovyan/jupyterlab-git/setupbase.py", line 387, in run
        raise ValueError(('missing files: %s' % missing))
    ValueError: missing files: ['/home/jovyan/jupyterlab-git/lib/git.js']
    ----------------------------------------
  Rolling back uninstall of jupyterlab-git
  Moving to /opt/conda/lib/python3.7/site-packages/jupyterlab_git-0.8.1.dist-info/
   from /opt/conda/lib/python3.7/site-packages/~upyterlab_git-0.8.1.dist-info
  Moving to /opt/conda/lib/python3.7/site-packages/jupyterlab_git/
   from /opt/conda/lib/python3.7/site-packages/~upyterlab_git
  Moving to /opt/conda/lib/python3.7/site-packages/tests/__init__.py
   from /tmp/pip-uninstall-o3qv8a7_/__init__.py
  Moving to /opt/conda/lib/python3.7/site-packages/tests/__pycache__/__init__.cpython-37.pyc
   from /tmp/pip-uninstall-o3qv8a7_/__pycache__/__init__.cpython-37.pyc
  Moving to /opt/conda/lib/python3.7/site-packages/tests/unit/
   from /opt/conda/lib/python3.7/site-packages/tests/~nit
ERROR: Command errored out with exit status 1: /opt/conda/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jovyan/jupyterlab-git/setup.py'"'"'; __file__='"'"'/home/jovyan/jupyterlab-git/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by fcollonval** [comment]
Thx for reporting the error. 

First of all are you sure you want to install the package in development mode. If not just drop the `-e` option in the pip install command.

`yarn` cannot be found. Meaning we are definitely having an error. Could you run the command `npm install -g yarn` before the pip command? It should allow you to install the extension.

**Comment by ggosiang** [comment]
@fcollonval 

Thank you! It works!
Now that I can install it without error.

**Comment by fcollonval** [comment]
Your welcome. I just keep this open as we should correct some dependencies to ensure it works like you try it.
