### ISSUE TITLE
`pexpect.spawn` does not support Windows

### ISSUE THREAD

**Issue by fcollonval** [jupyterlab/jupyterlab-git#492]
Per the documentation, the currently used `pexpect.spawn` to handle git authentication does not support Windows:
https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows

For Windows,  they recommand:
> Pexpect can be used on Windows to wait for a pattern to be produced by a child process, using pexpect.popen_spawn.PopenSpawn, or a file descriptor, using pexpect.fdpexpect.fdspawn.

**Comment by ktaletsk** [comment]
Documentation also says "PopenSpawn is not a direct replacement for spawn". That suggests to me that we would need to add separate implementation of GitAuthInputWrapper for Windows. Any thoughts on that? I am willing to help if needed.

**Comment by fcollonval** [comment]
@ktaletsk thank you for kicking in. Any help would be appreciated 😄 

Your proposal to handle Windows specifically is fine for me.

**Comment by fcollonval** [comment]
Entering passwords with `pexpect` is always going to be a little shaky. I did some research, and it looks like it should be possible to pass auth to git via the `env` arg in `subprocess.Popen`. The key is the `GIT_ASKPASS` env var. I'll play around with it and see if I can get a working prototype.

Refs:
https://stackoverflow.com/q/1456269/425458
https://serverfault.com/a/976927/58565
https://github.com/libgit2/pygit2
https://coolaj86.com/articles/vanilla-devops-git-credentials-cheatsheet/
https://git-scm.com/docs/git-credential-store
https://git-scm.com/docs/gitcredentials
https://git-scm.com/book/en/v2/Git-Tools-Credential-Storage
https://dev.to/pratham/custom-git-credential-helper-pfa
https://stackoverflow.com/a/10054470/425458
https://stackoverflow.com/q/5343068/425458
https://git-scm.com/docs/api-credentials
https://alanedwardes.com/blog/posts/git-username-password-environment-variables/

_Originally posted by @telamonian in https://github.com/jupyterlab/jupyterlab-git/pull/493#issuecomment-568840306_

**Comment by jaipreet-s** [comment]
This would also be a good opportunity to start adding integration testing + testing on windows in the CI setup

1. **Integration Testing**:  Use the server REST API to perform Git push/pull actions against a test Git repository
2. **CI**: Run these tests across Windows and Linux. Looks like [travis supports Windows now](https://docs.travis-ci.com/user/reference/windows/) so we may not have to overhaul the CI setup

**Comment by fcollonval** [comment]
Some simple example of using `GIT_ASKPASS` to set username and password from environment variables (for Linux): https://stackoverflow.com/questions/68344358/git-askpass-with-user-and-password

**Comment by Conor-Smith1** [comment]
I'm still getting this error: 

Traceback (most recent call last): File "C:\Users\conor\anaconda3\lib\site-packages\jupyterlab_git\git.py", line 135, in execute code, output, error = await call_subprocess_with_authentication( File "C:\Users\conor\anaconda3\lib\site-packages\jupyterlab_git\git.py", line 71, in call_subprocess_with_authentication p = pexpect.spawn( AttributeError: module 'pexpect' has no attribute 'spawn'

Has the pexpect issue not been resolved, meaning this cannot be used in Windows?

**Comment by fcollonval** [comment]
For now the handling of authentication by the extension is not working on Windows due to the limitation you are mentioning (reference issue https://github.com/jupyterlab/jupyterlab-git/issues/492).

One way to solve it is to set up a credential helper to deal with the authentication for you. For that you will need to use [Git for Windows](https://gitforwindows.org/). Then I think, it will work out of the box and prompt with a dialog if your credentials are required.

> Originally posted at https://github.com/jupyterlab/jupyterlab-git/discussions/1085#discussioncomment-2324757

**Comment by Conor-Smith1** [comment]
Ok, I ended up having to just push from Git for Windows and do all other operations in JupyterLab. A little annoying, but not too bad. Having used this functionality on Linux it is quite nice, hopefully it comes to Windows some day. Thanks for the help!
