### ISSUE TITLE
Error loading server extension jupyterlab_git

### ISSUE THREAD

**Issue by Filiprb** [jupyterlab/jupyterlab-git#827]
Hi,

I have problem with the server extension. When running ``jupyter serverextension list`` I get:

```
config dir: C:\Users\####\.jupyter
    jupyterlab_git enabled
    - Validating...
Error loading server extension jupyterlab_git
      X is jupyterlab_git importable?
config dir: C:\Users\####\Anaconda3\etc\jupyter
    jupyterlab enabled
    - Validating...
      jupyterlab 2.2.9 ok
    nbdime enabled
    - Validating...
      nbdime 2.1.0 ok
    jupyter_nbextensions_configurator enabled
    - Validating...
      jupyter_nbextensions_configurator 0.4.1 ok
```

I have run ``pip install --upgrade jupyterlab jupyterlab-git `` and ``jupyter lab build `` and tested several different options. Here are some logs from when launching Jupyter Lab 

```
[I 18:47:06.745 LabApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 18:47:07.099 LabApp] JupyterLab extension loaded from c:\users\####\anaconda3\lib\site-packages\jupyterlab
[I 18:47:07.099 LabApp] JupyterLab application directory is c:\users\####\anaconda3\share\jupyter\lab
[W 18:47:07.102 LabApp] Error loading server extension jupyterlab_git
    Traceback (most recent call last):
      File "c:\users\####\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "c:\users\filip.bjornsjo\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named jupyterlab_git 
```

What is a possible solution to my issue?

**Comment by EgorenkovMV** [comment]
Did you found out how to fix this issue?

**Comment by GomesNayagam** [comment]
i have the same problem, not sure what i am missing

**Comment by fcollonval** [comment]
@GomesNayagam could you please open z new issue and report the versions used and log produced for your installation
