### ISSUE TITLE
Development install fails on Windows

### ISSUE THREAD

**Issue by ktaletsk** [jupyterlab/jupyterlab-git#898]
## Description

Trying to work on some Windows-related issues in this repo and couldn't do development install. I tried on multiple Windows machines and I'm having the same issues on both, which I didn't on Linux or Mac. Would love to fix that but need some help. If Windows has some limitations for developing the plugin/or need special instructions, we should update the docs.

## Reproduce

1. Create new conda environment: `conda create -y -n jupyterlab_dev python=3.8`
2. Activate new environment: `conda activate jupyterlab_dev`
3. Install package in development mode:
```
pip install -e .[dev]
pre-commit install
```
4. Link your development version of the extension with JupyterLab
`jupyter labextension develop . --overwrite`

It errors out here. Full error log:

```
Installing c:\users\ktale\jupyterlab-git\jupyterlab_git\labextension -> @jupyterlab/git
Removing: c:\users\ktale\miniconda3\envs\jupyterlab_dev\share\jupyter\labextensions\@jupyterlab\git
Symlinking: c:\users\ktale\miniconda3\envs\jupyterlab_dev\share\jupyter\labextensions\@jupyterlab\git -> c:\users\ktale\jupyterlab-git\jupyterlab_git\labextension
Traceback (most recent call last):

  File "c:\users\ktale\miniconda3\envs\jupyterlab_dev\lib\site-packages\jupyterlab\debuglog.py", line 47, in debug_logging
    yield

  File "c:\users\ktale\miniconda3\envs\jupyterlab_dev\lib\site-packages\jupyterlab\labextensions.py", line 128, in start
    ans = self.run_task()

  File "c:\users\ktale\miniconda3\envs\jupyterlab_dev\lib\site-packages\jupyterlab\labextensions.py", line 199, in run_task
    develop_labextension_py(arg, user=self.user, sys_prefix=self.sys_prefix, labextensions_dir=self.labextensions_dir, logger=self.log, overwrite=self.overwrite,

  File "c:\users\ktale\miniconda3\envs\jupyterlab_dev\lib\site-packages\jupyterlab\federated_labextensions.py", line 149, in develop_labextension_py
    full_dest = develop_labextension(

  File "c:\users\ktale\miniconda3\envs\jupyterlab_dev\lib\site-packages\jupyterlab\federated_labextensions.py", line 106, in develop_labextension
    os.symlink(path, full_dest)

OSError: [WinError 1314] A required privilege is not held by the client: 'c:\\users\\ktale\\jupyterlab-git\\jupyterlab_git\\labextension' -> 'c:\\users\\ktale\\miniconda3\\envs\\jupyterlab_dev\\share\\jupyter\\labextensions\\@jupyterlab\\git'

Exiting application: lab
```

## Expected behavior

The development version is linked successfully

## Context

Using the latest Miniconda with separate environment, Python 3.8. Bug reproducible on two Windows machines with Windows 10 Home and Windows 10 Pro.
Extension version: latest master branch

**Comment by ktaletsk** [comment]
Oops, I found this issue: https://github.com/jupyterlab/jupyterlab/issues/9564
