### ISSUE TITLE
out of the box install fails with AttributeError: 'ExtensionManager' object has no attribute '_extensions'

### ISSUE THREAD

**Issue by bostrick** [jupyterlab/jupyterlab-git#934]
## Description

out of the box install using pip on recent Fedora and not so recent RHEL fails...

     [xxx@catbus t]$ python --version 
     Python 3.9.4
    [xxx@catbus t]$ python -m venv venv                                                                                                              
    [xxx@catbus t]$ . venv/bin/activate                                                                                                              
    (venv) [xxx@catbus t]$ pip install -U pip setuptools wheel 
    ...
    (venv) [xxx@catbus t]$ pip install jupyterlab
    ... 
    Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 anyio-3.0.1 argon2-cffi-20.1.0 async-generator-1.10 attrs-21.2.0 babel-2.9.1 backcall-0.2.0 bleach-3.3.0 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 decorator-5.0.7 defusedxml-0.7.1 entrypoints-0.3 idna-2.10 ipykernel-5.5.4 ipython-7.23.1 ipython-genutils-0.2.0 jedi-0.18.0 jinja2-2.11.3 json5-0.9.5 jsonschema-3.2.0 jupyter-client-6.2.0 jupyter-core-4.7.1 jupyter-server-1.7.0 jupyterlab-3.0.15 jupyterlab-pygments-0.1.2 jupyterlab-server-2.5.1 matplotlib-inline-0.1.2 mistune-0.8.4 nbclassic-0.2.7 nbclient-0.5.3 nbconvert-6.0.7 nbformat-5.1.3 nest-asyncio-1.5.1 notebook-6.3.0 packaging-20.9 pandocfilters-1.4.3 parso-0.8.2 pexpect-4.8.0 pickleshare-0.7.5 prometheus-client-0.10.1 prompt-toolkit-3.0.18 ptyprocess-0.7.0 pycparser-2.20 pygments-2.9.0 pyparsing-2.4.7 pyrsistent-0.17.3 python-dateutil-2.8.1 pytz-2021.1 pyzmq-22.0.3 requests-2.25.1 six-1.16.0 sniffio-1.2.0 terminado-0.9.4 testpath-0.4.4 tornado-6.1 traitlets-5.0.5 urllib3-1.26.4 wcwidth-0.2.5 webencodings-0.5.1 websocket-client
    (venv) [xxx@catbus t]$ jupyter-lab
    [I 2021-05-10 19:39:14.464 ServerApp] jupyterlab | extension was successfully linked.
    [W 2021-05-10 19:39:14.635 ServerApp] 'ExtensionManager' object has no attribute '_extensions'
    Traceback (most recent call last):
      File "/home/bowe/proj/t/venv/bin/jupyter-lab", line 8, in <module>
        sys.exit(main())
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in 
    launch_instance
        serverapp = cls.initialize_server(argv=args)
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in 
    initialize_server
        serverapp.initialize(
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
        return method(app, *args, **kwargs)
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/serverapp.py", line 1855, in initialize
         point = self.extension_manager.extension_points[starter_extension]
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 290, in 
    extension_points
        extensions = self.extensions
      File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions
        nb = self._extensions.get("nbclassic")
    AttributeError: 'ExtensionManager' object has no attribute '_extensions'

## Reproduce

0. remove /etc/jupyter and $HOME/.jupyter to wipe any previous config
1. install recent python virtual env
2. update pip, setuptools, and wheel
3. install jupyterlab
4. fire up jupyter-lab with "jupyter lab"

## Expected behavior

jupyterlab goodness to fire up in a browser

## Context

- Python package version:
      Python 3.9.4
- Extension version:
     JupyterLab v3.0.15
- Git version:
     N/A
- Operating System and its version:
   Fedora 33, and RHLE 8.2

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.

(venv) [bowe@catbus t]$ jupyter lab --debug 
[D 2021-05-10 19:48:24.984 ServerApp] No files in /home/bowe/.ipython/nbextensions
[D 2021-05-10 19:48:24.984 ServerApp] Searching ['/home/bowe/proj/t', '/home/bowe/.jupyter', '/home/bowe/proj/t/venv/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 2021-05-10 19:48:24.985 ServerApp] Looking for jupyter_config in /etc/jupyter
[D 2021-05-10 19:48:24.985 ServerApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 2021-05-10 19:48:24.985 ServerApp] Looking for jupyter_config in /home/bowe/proj/t/venv/etc/jupyter
[D 2021-05-10 19:48:24.985 ServerApp] Looking for jupyter_config in /home/bowe/.jupyter
[D 2021-05-10 19:48:24.985 ServerApp] Looking for jupyter_config in /home/bowe/proj/t
[D 2021-05-10 19:48:24.986 ServerApp] Looking for jupyter_server_config in /etc/jupyter
[D 2021-05-10 19:48:24.986 ServerApp] Looking for jupyter_server_config in /usr/local/etc/jupyter
[D 2021-05-10 19:48:24.986 ServerApp] Looking for jupyter_server_config in /home/bowe/proj/t/venv/etc/jupyter
[D 2021-05-10 19:48:24.986 ServerApp] Looking for jupyter_server_config in /home/bowe/.jupyter
[D 2021-05-10 19:48:24.986 ServerApp] Looking for jupyter_server_config in /home/bowe/proj/t
[D 2021-05-10 19:48:24.988 ServerApp] Paths used for configuration of jupyter_server_config: 
        /etc/jupyter/jupyter_server_config.json
[D 2021-05-10 19:48:24.988 ServerApp] Paths used for configuration of jupyter_server_config: 
        /usr/local/etc/jupyter/jupyter_server_config.json
[D 2021-05-10 19:48:24.988 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/bowe/proj/t/venv/etc/jupyter/jupyter_server_config.d/jupyterlab.json
        /home/bowe/proj/t/venv/etc/jupyter/jupyter_server_config.d/nbclassic.json
        /home/bowe/proj/t/venv/etc/jupyter/jupyter_server_config.json
[D 2021-05-10 19:48:24.989 ServerApp] Paths used for configuration of jupyter_server_config: 
        /home/bowe/.jupyter/jupyter_server_config.json
[D 2021-05-10 19:48:25.003 LabApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue {'update': {'nbclassic': True}}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[I 2021-05-10 19:48:25.004 ServerApp] jupyterlab | extension was successfully linked.
[D 2021-05-10 19:48:25.012 NotebookApp] Config changed: {'NotebookApp': {}, 'ServerApp': {'log_level': 'DEBUG', 'jpserver_extensions': <LazyConfigValue value={'jupyterlab': True, 'nbclassic': True}>}, 'ExtensionApp': {'log_level': 'DEBUG'}}
[D 2021-05-10 19:48:25.170 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/bowe/.jupyter/jupyter_notebook_config.json
[D 2021-05-10 19:48:25.171 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 19:48:25.171 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /usr/local/etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 19:48:25.172 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/bowe/proj/t/venv/etc/jupyter/jupyter_notebook_config.d/jupyterlab.json
        /home/bowe/proj/t/venv/etc/jupyter/jupyter_notebook_config.json
[D 2021-05-10 19:48:25.172 ServerApp] Paths used for configuration of jupyter_notebook_config: 
        /home/bowe/.jupyter/jupyter_notebook_config.json
[W 2021-05-10 19:48:25.172 ServerApp] 'ExtensionManager' object has no attribute '_extensions'
Traceback (most recent call last):
  File "/home/bowe/proj/t/venv/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
    serverapp.initialize(
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/serverapp.py", line 1855, in initialize
    point = self.extension_manager.extension_points[starter_extension]
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/jupyter_server/extension/manager.py", line 290, in extension_points
    extensions = self.extensions
  File "/home/bowe/proj/t/venv/lib64/python3.9/site-packages/nbclassic/nbserver.py", line 80, in extensions
    nb = self._extensions.get("nbclassic")
AttributeError: 'ExtensionManager' object has no attribute '_extensions'

</pre>
</details>

<details><summary>Web Browser Output</summary>
<pre>
Paste the output from your browser web console here.
</pre>
</details>

**Comment by bostrick** [comment]
oof...wrong repo :(...
